### ISSUE TITLE
Slight differences between Binance.com and Binance-futures

### ISSUE THREAD

**Issue by hbizot** [oliver-zehentleitner/unicorn_fy#1]
**Is your feature request related to a problem? Please describe.**
The response message from a aggTrade stream is slightly different than than that from Binance.com. The resonse I get is:
{"stream":"btcusdt@aggTrade","data":{"e":"aggTrade","E":1573576417345,"a":6292316,"s":"BTCUSDT","p":"8718.19","q":"0.792","f":8414086,"l":8414086,"T":1573576417240,"m":true}}

This key doen't exist for futures:
stream_data['data']['M']

**Describe the solution you'd like**

Remove this part in method 'binance_websocket':
'ignore': stream_data['data']['M']

in:
        if stream_data['data']['e'] == 'aggTrade':
            unicorn_fied_data = {'stream_type': stream_data['stream'],
                                 'event_type': stream_data['data']['e'],
                                 'event_time': stream_data['data']['E'],
                                 'symbol': stream_data['data']['s'],
                                 'aggregate_trade_id': stream_data['data']['a'],
                                 'price': stream_data['data']['p'],
                                 'quantity': stream_data['data']['q'],
                                 'first_trade_id': stream_data['data']['f'],
                                 'last_trade_id': stream_data['data']['l'],
                                 'trade_time': stream_data['data']['T'],
                                 'is_market_maker': stream_data['data']['m'],
-->                            'ignore': stream_data['data']['M']                 <--             }

since it's not used anyway.

Thanks.

**Describe alternatives you've considered**

**Additional context**

**Comment by oliver-zehentleitner** [comment]
I only mention this, because i see your github account is very new.

If you want, you can fork the repository and create a pull request. Its not much more work for you than creating this issue and i am able to merge the code after a review. Your benefit is that you get added to contributors and maybe its faster pushed to pypi because its less work for me :)

tell me if you want to try it!
