### ISSUE TITLE
ModuleNotFoundError: No module named 'unicorn_fy.unicorn_fy'; 'unicorn_fy' is not a package

### ISSUE THREAD

**Issue by uggel** [oliver-zehentleitner/unicorn_fy#9]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you using the module on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?
- [ ] Are you using the module on a Raspberry Pi?

#### Operating System? (include version)
- [x ] macOS
- [ ] Windows
- [x ] Linux (include flavour)

#### Exact Python Version?
``` 
Python 3.8.5
```

#### Pip Version?
``` 
pip 20.2.2
```

#### Description of your issue

```
ModuleNotFoundError: No module named 'unicorn_fy.unicorn_fy'; 'unicorn_fy' is not a package

I've fixed this for  unicorn-binance-websocket-api already. This is the same issue. The module is packaged as if it was a python script
```

**Comment by uggel** [comment]
fixed

**Comment by oliver-zehentleitner** [comment]
Thank you!!
https://github.com/oliver-zehentleitner/unicorn_fy/releases/tag/0.5.0
